"Usage:\n"
"\n"
"  minmail [files]\n"
"  minmail --wreak-havok [files]\n"
"\n"
"Description:\n"
"\n"
"  Extract parts of RFC 822 message files, such as those found beneath\n"
"  ~/Maildir, into separate files in a subdirectory named \"pieces\" that\n"
"  is created if necessary in the current working directory.\n"
"\n"
"  In the first form (without --wreak-havok), the original mail files\n"
"  are untouched, and the pieces subdirectory is populated.\n"
"\n"
"  If --wreak-havok is given, the original mail files will be\n"
"  overwritten with \"minimal\" RFC 822 messages that have:\n"
"\n"
"  1. no attachments\n"
"\n"
"  2. no alternate parts (text/plain if available, otherwise text/html)\n"
"\n"
"  3. fewer mail headers\n"
"\n"
"Options:\n"
"\n"
"  --wreak-havok   # modify the original mail file(s)\n"
"\n"
"Examples:\n"
"\n"
"  # Extract parts from a single message into pieces/ .  E.g.,\n"
"  # pieces/20210615.195257.j@example.com.01.txt\n"
"  # pieces/20210615.195257.j@example.com.02.html\n"
"  # pieces/20210615.195257.j@example.com.03.png\n"
"  minmail message.eml  # creates files in pieces, e.g.,\n"
"\n"
"  # Extract parts from all mail files in a single Maildir folder named\n"
"  # \"Read\".\n"
"  find ~/Maildir/Read -maxdepth 2 -type f | xargs minmail\n"
"\n"
"  # In addition to extracting parts, modify the original message to\n"
"  # make it minimal.\n"
"  minmail --wreak-havok message.eml\n"
"\n"
"Caveats:\n"
"\n"
"  THIS PROGRAM MAY DESTROY YOUR MAIL.\n"
"\n"
"  MAKE A BACKUP BEFORE USING.\n"
"\n"
"  CAVEAT EMPTOR.\n"
